GET / HTTP/1.1
Host: localhost:3000
Authorization: Bearer <put your bearer token here>

###
POST /signup HTTP/1.1
Host: localhost:3000
content-type: application/json

{
    "email": "sample443",
    "password": "test password"
}

###
POST http://localhost:3000/signin/ HTTP/1.1
content-type: application/json

{
    "email": "sample443",
    "password": "test password"
}